version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bd_vat_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes: [ "pgdata:/var/lib/postgresql/data" ]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  backend:
    build: { context: ./backend, dockerfile: Dockerfile }
    environment:
      DJANGO_SETTINGS_MODULE: vatmanager.settings
      DB_NAME: bd_vat_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: "5432"
      REDIS_URL: redis://redis:6379/0
      ALLOWED_HOSTS: "*"
      COMPANY_NAME: "VAT Consultancy Firm"
      APP_BRAND: "MH Rakib VAT Consultant (NBR)"
    depends_on: [ db, redis ]
    ports: ["8000:8000"]

  worker:
    build: { context: ./backend, dockerfile: Dockerfile }
    command: ["bash","-lc","celery -A vatmanager worker -l info"]
    environment:
      DJANGO_SETTINGS_MODULE: vatmanager.settings
      DB_NAME: bd_vat_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: "5432"
      REDIS_URL: redis://redis:6379/0
    depends_on: [ db, redis ]

  beat:
    build: { context: ./backend, dockerfile: Dockerfile }
    command: ["bash","-lc","celery -A vatmanager beat -l info"]
    environment:
      DJANGO_SETTINGS_MODULE: vatmanager.settings
      DB_NAME: bd_vat_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: "5432"
      REDIS_URL: redis://redis:6379/0
    depends_on: [ db, redis ]

  frontend:
    build: { context: ./frontend, dockerfile: Dockerfile }
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8000/api
      NEXT_PUBLIC_BRAND: "MH Rakib VAT Consultant (NBR) — VAT Consultancy Firm"
    ports: ["3000:3000"]
    depends_on: [ backend ]

volumes:
  pgdata:
